apiVersion: v1
kind: Service
metadata:
  name: java
  labels:
    app: java
spec:
  type: nodeport
 ports:
   -port: 8080
    targetPort: 8080
    nodePort: 30003
  selector:
    matchLabels:
      app: java
