kind: Service
apiVersion: v1
metadata:
  name: java-service
spec:
  type: NodePort 

  ports:
    - nodePort: 31234

    - port: 8080

    - targetPort: 8080

  selector:
    matchLabels:
      app: java
