FROM openjdk
ADD target/spring-boot-crud-operation-0.0.1-SNAPSHOT.jar spring-boot-crud-operation-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java" "-jar", "spring-boot-crud-operation-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080
